name: Bug Report
description: 报告 React Native Gromore 中的错误。
labels: ["Needs: Triage :mag:"]
body:
  - type: markdown
    attributes:
      value: "## 向 React Native Gromore 报告错误"
  - type: markdown
    attributes:
      value: |
        感谢您报告 React Native Gromore 的问题。
  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 清晰简洁的描述 bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 复现步骤
      description: 按照以下模版填写复现问题的步骤
      placeholder: |
        1. 使用 `yarn android` 安装应用程序
        2. 点击首页上的按钮
        3. 注意崩溃情况
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: React Native 版本
      description: 问题复现的 react-native 版本
      placeholder: "0.73.0"
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: 受影响的平台
      description: 请选择您正在开发的平台，以及您用于构建的操作系统
      multiple: true
      options:
        - Runtime - Android
        - Runtime - iOS
        - Runtime - Web
        - Runtime - Desktop
        - Build - MacOS
        - Build - Windows
        - Build - Linux
        - Other (please specify)
    validations:
      required: true
  - type: textarea
    id: react-native-info
    attributes:
      label: 命令`npx react-native info` 的输出
      description: 在您的终端执行 `npx react-native info`, 将结果复制并粘贴在这里
      placeholder: |
        在这里粘贴 `npx react-native info` 的结果。输出类似：
        ...
        System:
          OS: macOS 14.1.1
          CPU: (10) arm64 Apple M1 Max
          Memory: 417.81 MB / 64.00 GB
          Shell:
            version: "5.9"
            path: /bin/zsh
        Binaries:
          Node: ...
            version: 18.14.0
        ...
      render: text
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: 堆栈跟踪或日志
      description: 请提供您的崩溃或失败的堆栈跟踪或日志
      render: text
      placeholder: |
        请在这里粘贴您的堆栈跟踪和日志。其信息类似：

        java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfabricjni.so caused by: com.facebook.react.fabric.StateWrapperImpl result: 0
            at com.facebook.soloader.SoLoader.g(Unknown Source:341)
            at com.facebook.soloader.SoLoader.t(Unknown Source:124)
            at com.facebook.soloader.SoLoader.s(Unknown Source:2)
            at com.facebook.soloader.SoLoader.q(Unknown Source:42)
            at com.facebook.soloader.SoLoader.p(Unknown Source:1)
            ...
    validations:
      required: true
  # - type: input
  #   id: reproducer
  #   attributes:
  #     label: Reproducer
  #     description: A link to a Expo Snack or a public repository that reproduces this bug, using [this template](https://github.com/react-native-community/reproducer-react-native). Reproducers are **mandatory**.
  #     placeholder: "https://github.com/<myuser>/<myreproducer>"
  #   validations:
  #     required: true