name: "Check Version for Gromore SDK"

on:
  push:
    branches:
      - dev/ops
  schedule:
    - cron: "0 1 * * *"  # 每天凌晨 1 点
  workflow_dispatch:  # 允许手动触发

env:
  # Setting an environment variable with the value of a configuration variable
  USER_TOKEN: ${{ secrets.MY_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
  USER_REP: ${{ vars.USER_REP || github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Request API to Get IOS Version
      id: get-ios-version
      run: |
        response=$(curl -s http://gromore.ads.zmkj6.top/api/logs/ios?format=json)
        api_version=$(echo $response | jq -r -e '.data.Version')
        download_url=$(echo $response | jq -r '.data.DownloadUrl')

        echo "IOS SDK Get API version is $api_version   download url $download_url"
        echo "IOS_API_VERSION=$api_version" >> $GITHUB_ENV

    - name: Get Latest Ios Issue Version
      id: get-ios-latest-issue
      run: |
        response=$(curl -s -H "Authorization: Bearer ${{ env.USER_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ env.USER_REP }}/issues?labels=ios-version)

        ios_latest_issue=$(echo "$response" | jq -r -e '.[0].title' | sed -n 's/^IOS SDK Version //p' || echo "0")
        latest_issue=$(echo "$response" | jq -r -e '.[0]')
        echo "Latest issue version is $latest_issue"
        echo "IOS Latest issue version is $ios_latest_issue"
        echo "IOS_LATEST_ISSUE_VERSION=${ios_latest_issue}" >> $GITHUB_ENV

    - name: Compare Versions and Create Issue if Newer (IOS)
      run: |
        if [ "${{ env.IOS_API_VERSION }}" != "${{ env.IOS_LATEST_ISSUE_VERSION }}" ]; then
          echo "Creating issue for version ${{ env.IOS_API_VERSION }}"
          echo "New Android SDK version detected: ${{ env.IOS_API_VERSION }}"
          echo "create_tag=true" >> $GITHUB_ENV
          gh issue create \
          --title "IOS SDK Version ${{ env.IOS_API_VERSION }}" \
          --body "Gromore a new ios version ${{ env.IOS_API_VERSION }} has been released. @PBK-B @gaoxuan-haxibiao, please review." \
          --label "ios-version" \
          --repo ${{ env.USER_REP }}
        else
          echo "Version has not changed."
          echo "create_tag=false" >> $GITHUB_ENV
        fi  
        
    - name: Create IOS Tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch --tags
        # 如果没有任何 tag，则直接创建当前版本的 tag
        if [ -z "$(git tag -l)" ]; then
          echo "No tags found, creating initial IOS tag ios/${{ env.IOS_API_VERSION }}"
          git tag ios/${{ env.IOS_API_VERSION }}
          git push origin ios/${{ env.IOS_API_VERSION }}
          echo "create_tag=true" >> $GITHUB_ENV
        elif [ "${{ env.create_tag }}" = "true" ]; then
          git tag ios/${{ env.IOS_API_VERSION }}
          git push origin ios/${{ env.IOS_API_VERSION }}
        else
          echo "Skip creating IOS tag."
        fi

    - name: Download IOS SDK Logs
      if: env.create_tag == 'true'
      run: |
        curl -L "${download_url}" -o ios-${{ env.IOS_API_VERSION }}.zip
        echo "DOWNLOADED_FILE=ios-${{ env.IOS_API_VERSION }}.zip" >> $GITHUB_ENV

    - name: Upload IOS Release
      if: env.create_tag == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.DOWNLOADED_FILE }}
        tag: ios/${{ env.IOS_API_VERSION }}
        body: "Gromore IOS SDK logs for version ${{ env.IOS_API_VERSION }}"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Request API to Get Android Version
      id: get-android-version
      run: |
        response=$(curl -s http://gromore.ads.zmkj6.top/api/logs/android?format=json)
        api_version=$(echo $response | jq -r -e '.data.Version')
        download_url=$(echo $response | jq -r '.data.DownloadUrl')

        echo "Android SDK Get API version is $api_version   download url $download_url"
        echo "ANDROID_API_VERSION=$api_version" >> $GITHUB_ENV

    - name: Get Latest Issue Version
      id: get-android-latest-issue
      run: |
        response=$(curl -s -H "Authorization: Bearer ${{ env.USER_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ env.USER_REP }}/issues?labels=android-version)
        
        android_latest_issue=$(echo "$response" | jq -r -e '.[0].title' | sed -n 's/^Android SDK Version //p' || echo "0")
        
        echo "Latest issue version is $android_latest_issue"
        echo "ANDROID_LATEST_ISSUE_VERSION=${android_latest_issue}" >> $GITHUB_ENV

    - name: Compare Versions and Create Issue if Newer (Android)
      id: compare-android
      run: |
        if [ "${{ env.ANDROID_API_VERSION }}" != "${{ env.ANDROID_LATEST_ISSUE_VERSION }}" ]; then
          echo "New Android SDK version detected: ${{ env.ANDROID_API_VERSION }}"
          echo "create_tag=true" >> $GITHUB_ENV
          echo "Creating issue for version ${{ env.ANDROID_API_VERSION }}"
          gh issue create \
          --title "Android SDK Version ${{ env.ANDROID_API_VERSION }}" \
          --body "Gromore a new android version ${{ env.ANDROID_API_VERSION }} has been released. @PBK-B @gaoxuan-haxibiao, please review." \
          --label "android-version" \
          --repo ${{ env.USER_REP }}
        else
          echo "Version has not changed."
          echo "create_tag=false" >> $GITHUB_ENV
        fi
      
    - name: Create Android Tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch --tags
        # 如果没有任何 tag，则直接创建当前版本的 tag
        if [ -z "$(git tag -l)" ]; then
          echo "No tags found, creating initial Android tag android/${{ env.ANDROID_API_VERSION }}"
          git tag android/${{ env.ANDROID_API_VERSION }}
          git push origin android/${{ env.ANDROID_API_VERSION }}
          echo "create_tag=true" >> $GITHUB_ENV
        elif [ "${{ env.create_tag }}" = "true" ]; then
          git tag android/${{ env.ANDROID_API_VERSION }}
          git push origin android/${{ env.ANDROID_API_VERSION }}
        else
          echo "Skip creating Android tag."
        fi

    - name: Create Android Tag
      if: env.create_tag == 'true'
      run: |
        curl -L "${download_url}" -o android-${{ env.ANDROID_API_VERSION }}.zip
        echo "DOWNLOADED_FILE=android-${{ env.ANDROID_API_VERSION }}.zip" >> $GITHUB_ENV

    - name: Upload Android Release
      if: env.create_tag == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.DOWNLOADED_FILE }}
        tag: android/${{ env.ANDROID_API_VERSION }}
        body: "Gromore Android SDK logs for version ${{ env.ANDROID_API_VERSION }}"
        token: ${{ secrets.GITHUB_TOKEN }}
      
